### ISSUE TITLE
Error: Invalid CSS after "    $keys: list":

### ISSUE THREAD

**Issue by dompl** [lolmaus/breakpoint-slicer#39]
Hi.

Thank you for your hard work on the new version. Looks very promising!
 
When I switched though Im getting the following error message:

Message:
    node_modules/breakpoint-slicer/index.scss
Error: Invalid CSS after "    $keys: list": expected expression (e.g. 1px, bold), was ".append($keys, $key"
        on line 162 of node_modules/breakpoint-slicer/index.scss
        from line 24 of src/assets/scss/style.scss
       $keys: list.append($keys, $key);

Would you be able to advice please?

Thanks

**Comment by lolmaus** [comment]
Hi!

The new version of Breakpoint Slicier relies on [Sass Modules](https://sass-lang.com/blog/the-module-system-is-launched) — a modern way of organizing Sass code to prevent global namespace collisions and make the code easier to maintain.

Sass Modules are available in Dart Sass since version 1.23.0 on October 2019. 

Support for Sass Modules in libsass had been planned but was not implemented, since libsass was [deprecated](https://sass-lang.com/blog/libsass-is-deprecated) in October 2020.

Ruby Sass was [deprecated](https://sass-lang.com/blog/ruby-sass-is-deprecated) even earlier, in March 2018, with the release of Dart Sass 1.0.0, and reached its end of life in March 2019.

So currently the only modern, maintained Sass engine is Dart Sass. You should switch to it.

Note that the support for the old, `@import`-based module system will be dropped on 1 October 2022. This is gonna be breaking for all Sass apps and most libraries, so versions of Dart Sass after October 2022 will support the new Breakpoint Slicer but will not support many other libraries such as Bootstrap 5, which has recently been released without support for Sass Modules.

I don't know what platform you're on: the stack trace implies Node, but downloading from npm does not automatically mean you compile Sass with Node. If you do compile Sass with Node, then you should remove `node-sass` from your dependencies and add latest `sass`. It's the same package, just renamed. For other platforms, there should be updated packages too, but you'll have to look it up yourself.

Hopefully, it will go smoothly for you, but if you use additional wrappers over `node-sass` to integrate with your framework, the wrapper package might require updating too.

***

I'm gonna close this ticket, but please don't hesitate to reply and keep the conversation going. I'm glad to be of help.

**Comment by lolmaus** [comment]
(edited previous comment, please read it on GitHub and not in email)
